services:
    nginx:
        container_name: dciwebserver
        #restart: always
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - uploads_volume:/var/www/uploads
            - static_volume:/var/www/staticfiles
        ports:
            - "80:80"
        depends_on:
            - web
    web:
        container_name: dciwebapp
        image: dciwebappimg:v1
        build: .
        #restart: always
        ports:
            - "8001:8001"
        env_file:
            - .env
        volumes:
            - .:/app
            - uploads_volume:/app/uploads
            - static_volume:/app/staticfiles
        depends_on:
            - db
        command: >
            sh -c "python manage.py makemigrations accounts && python manage.py makemigrations && python manage.py migrate --no-input && python manage.py collectstatic --no-input && gunicorn django_project.wsgi:application -b 0.0.0.0:8001"

    db:
        container_name: dcinewsdbserver
        image: postgres:16
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        env_file:
            - .env
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
    postgres_data:
    uploads_volume:
    static_volume:
