# Generated by Django 5.0.2 on 2024-02-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('first_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=50)),
                ('password', models.CharField(max_length=15)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
