# Generated by Django 5.0.2 on 2024-03-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('inmatricolation', models.DateField(help_text="Date as 'Year/month'")),
                ('price', models.FloatField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
