# Generated by Django 5.0.2 on 2024-03-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0002_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
