# Generated by Django 5.0.2 on 2024-03-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0003_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='is_autenticated',
            field=models.BooleanField(auto_created=True, default=True, editable=False),
        ),
    ]
