# Generated by Django 5.0.2 on 2024-03-11 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0004_guestuser_is_autenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestuser',
            name='is_autenticated',
        ),
    ]
