# Generated by Django 5.0.2 on 2024-02-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_autos_remove_order_item_remove_order_user_delete_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='autos',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='autos',
            name='selled',
            field=models.IntegerField(null=True),
        ),
    ]
