# Generated by Django 5.0.2 on 2024-03-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='disponible',
            field=models.BooleanField(auto_created=True, default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='inmatricolation',
            field=models.DateField(null=True),
        ),
    ]
