# Generated by Django 5.0.2 on 2024-03-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(auto_created=True, default=False, editable=False),
        ),
    ]
