# Generated by Django 5.0.2 on 2024-02-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('inmatricolation', models.DateField(help_text="Date as 'Year/month'")),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('selled', models.IntegerField(null=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
