# Generated by Django 5.0.2 on 2024-02-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
